### ISSUE TITLE
install in laravel "laravel/framework": "5.2"

### ISSUE THREAD

**Issue by shahin1979** [IftekherSunny/Laravel-Flash#2]
Is it possible to install it in "laravel/framework": "5.2" ?

**Comment by IftekherSunny** [comment]
@shahin1979 yes.

**Comment by shahin1979** [comment]
I have tried but failed as the following:

sudo composer require illuminate/session 5.1.*
./composer.json has been updated
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.



  Problem 1
    - Conclusion: don't install laravel/framework 5.2.x-dev
    - Conclusion: don't install laravel/framework v5.2.29
    - Conclusion: don't install laravel/framework v5.2.28
    - Conclusion: remove laravel/framework v5.2.27
    - Conclusion: don't install laravel/framework v5.2.27
    - Conclusion: don't install laravel/framework v5.2.26
    - Conclusion: don't install laravel/framework v5.2.25
    - Conclusion: don't install laravel/framework v5.2.24
    - Conclusion: don't install laravel/framework v5.2.23
    - Conclusion: don't install laravel/framework v5.2.22
    - Conclusion: don't install laravel/framework v5.2.21
    - Conclusion: don't install laravel/framework v5.2.20
    - Conclusion: don't install laravel/framework v5.2.19
    - Conclusion: don't install laravel/framework v5.2.18
    - Conclusion: don't install laravel/framework v5.2.17
    - Conclusion: don't install laravel/framework v5.2.16
    - Conclusion: don't install laravel/framework v5.2.15
    - Conclusion: don't install laravel/framework v5.2.14
    - Conclusion: don't install laravel/framework v5.2.13
    - Conclusion: don't install laravel/framework v5.2.12
    - Conclusion: don't install laravel/framework v5.2.11
    - Conclusion: don't install laravel/framework v5.2.10
    - Conclusion: don't install laravel/framework v5.2.9
    - Conclusion: don't install laravel/framework v5.2.8
    - Conclusion: don't install laravel/framework v5.2.7
    - Conclusion: don't install laravel/framework v5.2.6
    - Conclusion: don't install laravel/framework v5.2.5
    - Conclusion: don't install laravel/framework v5.2.4
    - Conclusion: don't install laravel/framework v5.2.3
    - Conclusion: don't install laravel/framework v5.2.2
    - Conclusion: don't install laravel/framework v5.2.1
    - Conclusion: don't install laravel/framework v5.2.0
    - Conclusion: don't install laravel/framework v5.2.0-beta1
    - illuminate/session 5.1.x-dev requires illuminate/contracts 5.1.* -> satisfiable by illuminate/contracts[5.1.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.8].
    - illuminate/session v5.1.1 requires illuminate/contracts 5.1.* -> satisfiable by illuminate/contracts[5.1.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.8].
    - illuminate/session v5.1.13 requires illuminate/contracts 5.1.* -> satisfiable by illuminate/contracts[5.1.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.8].
    - illuminate/session v5.1.16 requires illuminate/contracts 5.1.* -> satisfiable by illuminate/contracts[5.1.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.8].
    - illuminate/session v5.1.2 requires illuminate/contracts 5.1.* -> satisfiable by illuminate/contracts[5.1.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.8].
    - illuminate/session v5.1.20 requires illuminate/contracts 5.1.* -> satisfiable by illuminate/contracts[5.1.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.8].
    - illuminate/session v5.1.22 requires illuminate/contracts 5.1.* -> satisfiable by illuminate/contracts[5.1.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.8].
    - illuminate/session v5.1.25 requires illuminate/contracts 5.1.* -> satisfiable by illuminate/contracts[5.1.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.8].
    - illuminate/session v5.1.28 requires illuminate/contracts 5.1.* -> satisfiable by illuminate/contracts[5.1.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.8].
    - illuminate/session v5.1.30 requires illuminate/contracts 5.1.* -> satisfiable by illuminate/contracts[5.1.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.8].
    - illuminate/session v5.1.31 requires illuminate/contracts 5.1.* -> satisfiable by illuminate/contracts[5.1.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.8].
    - illuminate/session v5.1.6 requires illuminate/contracts 5.1.* -> satisfiable by illuminate/contracts[5.1.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.8].
ubdev@ubdev-Box:/project/inventory$ 
ubdev@ubdev-Box:/project/inventory$ sudo composer require sun/laravel-flash
[sudo] password for ubdev: 
Using version ^1.2 for sun/laravel-flash
./composer.json has been updated
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for sun/laravel-flash ^1.2 -> satisfiable by sun/laravel-flash[v1.2].
    - Conclusion: remove laravel/framework v5.2.27
    - Conclusion: don't install laravel/framework v5.2.27
    - sun/laravel-flash v1.2 requires illuminate/session 5.1.* -> satisfiable by illuminate/session[5.1.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.6, v5.1.8].
    - don't install illuminate/session 5.1.x-dev|don't install laravel/framework v5.2.27
    - don't install illuminate/session v5.1.1|don't install laravel/framework v5.2.27
    - don't install illuminate/session v5.1.13|don't install laravel/framework v5.2.27
    - don't install illuminate/session v5.1.16|don't install laravel/framework v5.2.27
    - don't install illuminate/session v5.1.2|don't install laravel/framework v5.2.27
    - don't install illuminate/session v5.1.20|don't install laravel/framework v5.2.27
    - don't install illuminate/session v5.1.22|don't install laravel/framework v5.2.27
    - don't install illuminate/session v5.1.25|don't install laravel/framework v5.2.27
    - don't install illuminate/session v5.1.28|don't install laravel/framework v5.2.27
    - don't install illuminate/session v5.1.30|don't install laravel/framework v5.2.27
    - don't install illuminate/session v5.1.31|don't install laravel/framework v5.2.27
    - don't install illuminate/session v5.1.6|don't install laravel/framework v5.2.27
    - don't install illuminate/session v5.1.8|don't install laravel/framework v5.2.27
    - Installation request for laravel/framework == 5.2.27.0 -> satisfiable by laravel/framework[v5.2.27].


Installation failed, reverting ./composer.json to its original content.


Please help

**Comment by shahin1979** [comment]
here in composer.json

{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2._",
        "laravelcollective/html": "5.2._"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9._",
        "phpunit/phpunit": "~4.0",
        "symfony/css-selector": "2.8._|3.0._",
        "symfony/dom-crawler": "2.8._|3.0.*"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "pre-update-cmd": [
            "php artisan clear-compiled"
        ],
        "post-update-cmd": [
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    },

```
"minimum-stability": "dev"
```

}

**Comment by shahin1979** [comment]
I have tried to install but getting error:

ubdev@ubdev-Box:/project/inventory$ sudo composer require sun/laravel-flash
[sudo] password for ubdev: 
Using version ^1.2 for sun/laravel-flash
./composer.json has been updated

> php artisan clear-compiled
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for sun/laravel-flash ^1.2 -> satisfiable by sun/laravel-flash[v1.2].
    - Conclusion: remove laravel/framework v5.2.27
    - Conclusion: don't install laravel/framework v5.2.27
    - sun/laravel-flash v1.2 requires illuminate/session 5.1.\* -> satisfiable by illuminate/session[5.1.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.6, v5.1.8].
    - don't install illuminate/session 5.1.x-dev|don't install laravel/framework v5.2.27
    - don't install illuminate/session v5.1.1|don't install laravel/framework v5.2.27
    - don't install illuminate/session v5.1.13|don't install laravel/framework v5.2.27
    - don't install illuminate/session v5.1.16|don't install laravel/framework v5.2.27
    - don't install illuminate/session v5.1.2|don't install laravel/framework v5.2.27
    - don't install illuminate/session v5.1.20|don't install laravel/framework v5.2.27
    - don't install illuminate/session v5.1.22|don't install laravel/framework v5.2.27
    - don't install illuminate/session v5.1.25|don't install laravel/framework v5.2.27
    - don't install illuminate/session v5.1.28|don't install laravel/framework v5.2.27
    - don't install illuminate/session v5.1.30|don't install laravel/framework v5.2.27
    - don't install illuminate/session v5.1.31|don't install laravel/framework v5.2.27
    - don't install illuminate/session v5.1.6|don't install laravel/framework v5.2.27
    - don't install illuminate/session v5.1.8|don't install laravel/framework v5.2.27
    - Installation request for laravel/framework == 5.2.27.0 -> satisfiable by laravel/framework[v5.2.27].

Installation failed, reverting ./composer.json to its original content.
ubdev@ubdev-Box:/project/inventory$ 

Please help

**Comment by IftekherSunny** [comment]
@shahin1979 thanks for your reply. I'm now fixing this problem.

**Comment by IftekherSunny** [comment]
Now, try to install

**Comment by shahin1979** [comment]
Thank You. Its now installed.
